### ISSUE TITLE
There is no implementation of the "GetProperty" method in the "NSelene.SeleneElement" type from the "NSelene" assembly.

### ISSUE THREAD

**Issue by Magadan84** [yashaka/NSelene#40] opened 2018-03-06 11:45 UTC
Hi,
I get the issue 

> There is no implementation of the "GetProperty" method in the "NSelene.SeleneElement" type from the "NSelene" assembly.

Seems that the issue related to the last updates of the ChromeDriver - 2.35, Selenium.WebDriver - 3.10.0, Selenium.Support - 3.10.0, NSelene - 0.0.0.6

Source

`public static void Login()`
        `{`
`  var loginBy = By.Id("Login");`
`            var passwordBy = By.Id("Password");`
`            Type(loginBy, adminLogin);`
`            Type(passwordBy, adminPassword);`
`            I.Find(By.XPath("//*[contains(@class,'btn _submit')]")).Click();`
`}`
        `public static void Type(By locator, string text)`
        `{`
           ` if (text == null) return;`
`            I.Find(locator).Clear();`
`           I.Find(locator).SendKeys(text);`
`        }`

The exception occurs on the Type method calling even without stepping into the method.

**Comment by denis-platonov** [comment] 2018-03-09 21:02
I think it is a duplicate of https://github.com/yashaka/NSelene/issues/39

**Comment by Magadan84** [comment] 2018-05-21 15:57
@yashaka please, fix this issue or give some advice how to get around the issue.

**Comment by yashaka** [comment] 2018-05-28 22:04
should be fixed now in https://www.nuget.org/packages/NSelene/0.0.0.7

**Closed by yashaka** 2018-05-28 22:04 UTC
